# Generated by Django 4.2 on 2026-04-28 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_numbers',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
        migrations.CreateModel(
            name='SeatMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.JSONField(default=dict)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_map', to='eventura.event')),
            ],
        ),
    ]
