# Generated by Django 4.2 on 2026-04-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventura', '0002_ticket_cancelled_at_ticket_seat_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seat_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
